version: '3.8'

services:
  backend:
    build: .
    container_name: toonzyai-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./static:/app/static
      - .:/app
      - ./service-account-key:/app/service-account-key
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key/key.json
      - VERTEX_PROJECT=extended-bongo-463404-r3
      - VERTEX_LOCATION=us-central1
      - GCS_PROJECT=extended-bongo-463404-r3
      - GCS_BUCKET=toonzyai-avatars

volumes:
  postgres_data:
 