"""add_stories_table

Revision ID: 133dda99c33f
Revises: 6df22bb7ade7
Create Date: 2025-07-16 14:02:17.778664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133dda99c33f'
down_revision = '6df22bb7ade7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('script_data', sa.Text(), nullable=False),
    sa.Column('style_data', sa.Text(), nullable=True),
    sa.Column('characters_data', sa.Text(), nullable=True),
    sa.Column('environments_data', sa.Text(), nullable=True),
    sa.Column('illustrations_data', sa.Text(), nullable=True),
    sa.Column('quiz_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stories')
    # ### end Alembic commands ###