"""add_animation_tables

Revision ID: 643fd125555a
Revises: 5dd78ca44e81
Create Date: 2025-06-26 14:02:48.799745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643fd125555a'
down_revision = '5dd78ca44e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animation_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_avatar_id', sa.UUID(), nullable=False),
    sa.Column('total_segments', sa.Integer(), nullable=False),
    sa.Column('animation_prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'ASSEMBLING', name='animationstatus'), nullable=False),
    sa.Column('final_video_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_avatar_id'], ['avatars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animation_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('animation_project_id', sa.UUID(), nullable=False),
    sa.Column('segment_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'ASSEMBLING', name='animationstatus'), nullable=False),
    sa.Column('start_frame_url', sa.String(), nullable=False),
    sa.Column('generated_video_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['animation_project_id'], ['animation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animation_segments')
    op.drop_table('animation_projects')
    # ### end Alembic commands ###