"""add animation_type to animation_projects

Revision ID: 6df22bb7ade7
Revises: f7f8f9f0f1f2
Create Date: 2025-07-13 16:01:05.824758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df22bb7ade7'
down_revision = 'f7f8f9f0f1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animation_projects', sa.Column('animation_type', sa.String(length=32), nullable=True))
    op.execute("UPDATE animation_projects SET animation_type = 'independent' WHERE animation_type IS NULL")
    op.alter_column('animation_projects', 'animation_type', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animation_projects', 'animation_type')
    # ### end Alembic commands ###