"""add_segment_prompt_for_user_control

Revision ID: d2d2a701d434
Revises: 643fd125555a
Create Date: 2025-06-30 15:19:57.342327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d2a701d434'
down_revision = '643fd125555a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animation_segments', sa.Column('segment_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animation_segments', 'segment_prompt')
    # ### end Alembic commands ###